name: Build Android APK

on:
  push:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل المشروع
        uses: actions/checkout@v6

      - name: تثبيت uv
        uses: astral-sh/setup-uv@v6

      - name: بناء APK
        run: |
          uv run flet build apk --yes --verbose

      - name: رفع APK
        uses: actions/upload-artifact@v7
        with:
          name: iraq-db-app-apk
          path: build/apk/*.apk
          if-no-files-found: error
